db:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=root"
        - "MYSQL_DATABASE=erp_medical"

        
engine:
    build: ./docker/engine/php/7.2
    volumes:
        - ".:/home/docker:rw"
    links:
        - "db:db"
    working_dir: "/home/docker"

front:
    image: nginx
    ports:
        - "80:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/home/docker:ro"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"

adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
