# DIRECCIÓN DEL ENRUTADOR GLOBAL................................................
app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /
#...............................................................................
# GESTIONAREMOS EL ENRUTADOR MEDIANTE '@AppBundle/Resources/config/routing.yml'
# PARA PODER CENTRALIZARLO......................................................

