# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# EXTENSIÓN DE TWIG PARA OBTENER LA INFORMACIÓN DE LA CIUDAD...
    # nombre del filtro a usar: 'AddressCityAllInformation'
    AddressCityAllInformation.twig_extension:
        class: AppBundle\Twig\AddressCityAllInformationExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# EXTENSIÓN DE TWIG PARA OBTENER LA TAGS EN LAS VISTA...
    # nombre del filtro a usar: 'GenerateTags'
    GenerateTags.twig_extension:
        class: AppBundle\Twig\GenerateTagsExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
# EXTENSIÓN DE TWIG PARA OBTENER LA JSON_DECODE...
    # nombre del filtro a usar: 'GenerateTags'
    JsonDecode.twig_extension:
        class: AppBundle\Twig\JsonDecodeExtension
        public: false
        arguments:
            $doctrine: "@doctrine"
        tags:
            - { name: twig.extension }      


