# ROUTING CREAR UNA NUEVA CLÍNICA
clinic_create:
    path: /clinic/create
    defaults: { _controller: AppBundle:Clinic:clinicCreate }
# ROUTING VER DATOS CLÍNICA
clinic_view:
    path: /clinic/{clinicNameUrl}
    defaults: { _controller: AppBundle:Clinic:clinicView }
# ROUTING VER DOCUMENTOS CLÍNICA
clinic_doc_list:
    path: /clinic/{clinicNameUrl}/documents
    defaults: { _controller: AppBundle:ClinicDoc:clinicDocList }

