####################################################################################
# ROUTING PARA LISTAR LAS HISTORIAS CLÍNICAS
medical_history_doc_remove:
    path: /{clinicNameUrl}/medicalhistory/{medicalHistoryNumber}/removedoc/{idDoc}
    defaults: { _controller: AppBundle:Documents:medicalHistoryDocRemove }
####################################################################################
# ROUTING PARA LISTAR LAS HISTORIAS CLÍNICAS
orthopodology_history_doc_remove:
    path: /{clinicNameUrl}/medicalhistory/{medicalHistoryNumber}/orthopodologyhistory/{registrationDate}/removedoc/{idDoc}
    defaults: { _controller: AppBundle:Documents:orthopodologyHistoryDocRemove }