# ROUTING PARA EL SCHEDULE
schedule_home:
    path: /{clinicNameUrl}/{userName}/schedule
    defaults: { _controller: AppBundle:Schedule:home }
schedule_config:
    path: /schedule_config/{userId}
    defaults: { _controller: AppBundle:Schedule:config, userId: null }
schedule_event_edit:
    path: /schedule_event_edit
    defaults: { _controller: AppBundle:Schedule:editTimeEventAjax }
schedule_event_remove:
    path: /{clinicNameUrl}/{userName}/schedule/remove
    defaults: { _controller: AppBundle:Schedule:removeEvent }
schedule_event_daterange:
    path: /{clinicNameUrl}/{userName}/schedule/daterange/
    defaults: { _controller: AppBundle:Schedule:dateRangeEventAjax }    