BackendBundle\Entity\AddressCcaa:
    type: entity
    table: address_ccaa
# indexes ############################################################# 
# /indexes ############################################################ 
# id ##################################################################     
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
# /id #################################################################
# fields ##############################################################                
    fields:
        ccaa:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
# /fields #############################################################
# manyToOne ########################################################### 
# /manyToOne ##########################################################
# oneToMany ########################################################### 
# /oneToMany ##########################################################                  
    lifecycleCallbacks: {  }
