BackendBundle\Entity\Documents:
    type: entity
    table: documents
    indexes:
        clinic:
            columns:
                - clinic
        business:
            columns:
                - business 
        medical_history:
            columns:
                - medical_history   
        orthopodology_history:
            columns:
                - orthopodology_history                                                
        type_content_doc:
            columns:
                - type_content_doc 
        type_doc:
            columns:
                - type_doc
        user_registerer:
            columns:
                - user_registerer
        user_modifier:
            columns:
                - user_modifier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        doc:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        registrationDate:
            type: datetime
            nullable: false
            column: registration_date
        modificationDate:
            type: datetime
            nullable: false
            column: modification_date
    manyToOne:
        clinic:
            targetEntity: Clinic
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: documentsList
            joinColumns:
                clinic:
                    referencedColumnName: id
            orphanRemoval: false        
        business:
            targetEntity: Business
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: documentsList
            joinColumns:
                business:
                    referencedColumnName: id
            orphanRemoval: false 
        medicalHistory:
            targetEntity: MedicalHistory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: documentsList
            joinColumns:
                medical_history:
                    referencedColumnName: id
            orphanRemoval: false
        orthopodologyHistory:
            targetEntity: OrthopodologyHistory
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: documentsList
            joinColumns:
                orthopodology_history:
                    referencedColumnName: id
            orphanRemoval: false                                    
        typeDoc:
            targetEntity: TypeDoc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_doc:
                    referencedColumnName: id
            orphanRemoval: false
        typeContentDoc:
            targetEntity: TypeContentDoc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_content_doc:
                    referencedColumnName: id
            orphanRemoval: false
        userModifier:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_modifier:
                    referencedColumnName: id
            orphanRemoval: false
        userRegisterer:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_registerer:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
