BackendBundle\Entity\InvoiceService:
    type: entity
    table: invoice_service
    indexes:
        tracing_service:
            columns:
                - tracing_service
        invoice:
            columns:
                - invoice
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        invoice:
            targetEntity: Invoice
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                invoice:
                    referencedColumnName: id
            orphanRemoval: false
        tracingService:
            targetEntity: TracingService
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tracing_service:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
