BackendBundle\Entity\ScheduleGoogleCalendar:
    type: entity
    table: schedule_google_calendar
    indexes:
        user:
            columns:
                - user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        refreshToken:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        googleCalendarId:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
