BackendBundle\Entity\TracingService:
    type: entity
    table: tracing_service
    repositoryClass: BackendBundle\Repository\TracingServiceRepository    
    indexes:
        tracing:
            columns:
                - tracing
        service:
            columns:
                - service
        invoice_issued:
            columns:
                - invoice_issued
        parent:
            columns:
                - parent
        user_registerer:
            columns:
                - user_registerer
        user_modifier:
            columns:
                - user_modifier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        discount:
            type: float
            nullable: true
            precision: 10
            scale: 0  
        countable:
            type: boolean
            nullable: false
            options:
                default: '1'
        consolidated:
            type: boolean
            nullable: false
            options:
                default: '0'                                      
        registrationDate:
            type: datetime
            nullable: false
            column: registration_date
        modificationDate:
            type: datetime
            nullable: true
            column: modification_date
# manyToOne ###########################################################
    manyToOne:
        # referencia ManyToOne de la Entidad # Tracing #
        tracing:
            targetEntity: Tracing
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            # inversedBy # hace referencia si a la relación OneToMany de la entidad # Tracing #
            inversedBy: tracingServiceList
            joinColumns:
                tracing:
                    referencedColumnName: id
            orphanRemoval: false
        invoiceIssued:
            targetEntity: InvoiceIssued
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                invoice_issued:
                    referencedColumnName: id
            orphanRemoval: false                   
        parent:
            targetEntity: TracingService
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: children
            joinColumns:
                parent:
                    referencedColumnName: id
            orphanRemoval: false            
        service:
            targetEntity: Service
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                service:
                    referencedColumnName: id
            orphanRemoval: false
        userRegisterer:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_registerer:
                    referencedColumnName: id
            orphanRemoval: false
        userModifier:
            targetEntity: User
            nullable: true
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_modifier:
                    referencedColumnName: id
            orphanRemoval: false
# /manyToOne ##########################################################
    oneToMany:
        # la eliminaremos cuando convirtamos
        children:
            targetEntity: TracingService
            mappedBy: parent
        # la eliminaremos cuando convirtamos
        paymentList:
            targetEntity: Payment
            mappedBy: tracingService 
        invoiceServiceList:
            targetEntity: InvoiceService
            mappedBy: tracingService                        
    lifecycleCallbacks: {  }
