BackendBundle\Entity\TracingService:
    type: entity
    table: tracing_service
    indexes:
        tracing:
            columns:
                - tracing
        service:
            columns:
                - service
        user_registerer:
            columns:
                - user_registerer
        user_modifier:
            columns:
                - user_modifier
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        registrationDate:
            type: datetime
            nullable: false
            column: registration_date
        modificationDate:
            type: datetime
            nullable: false
            column: modification_date
# manyToOne ###########################################################
    manyToOne:
        # referencia ManyToOne de la Entidad # Tracing #         
        tracing:
            targetEntity: Tracing
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            # inversedBy # hace referencia si a la relación OneToMany de la entidad # Tracing #               
            inversedBy: tracingServiceList
            joinColumns:
                tracing:
                    referencedColumnName: id
            orphanRemoval: false
        service:
            targetEntity: Service
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                service:
                    referencedColumnName: id
            orphanRemoval: false
        userRegisterer:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_registerer:
                    referencedColumnName: id
            orphanRemoval: false
        userModifier:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_modifier:
                    referencedColumnName: id
            orphanRemoval: false
# /manyToOne ##########################################################             
    lifecycleCallbacks: {  }
