BackendBundle\Entity\TypeTracing:
    type: entity
    table: type_tracing
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: type
        translate:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
