BackendBundle\Entity\TypeTaxInvoice:
    type: entity
    table: type_tax_invoice
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taxLevel:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: tax_level
        percent:
            type: float
            nullable: false
            precision: 10
            scale: 0
        registrationDate:
            type: datetime
            nullable: false
            column: registration_date
    lifecycleCallbacks: {  }
