BackendBundle\Entity\TypeContentDoc:
    type: entity
    table: type_content_doc
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
#            column: type
    lifecycleCallbacks: {  }