BackendBundle\Entity\TypeTax:
    type: entity
    table: type_tax
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        taxName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: tax_name
        percent:
            type: float
            nullable: false
            precision: 10
            scale: 0
        registrationDate:
            type: datetime
            nullable: false
            column: registration_date
    lifecycleCallbacks: {  }
