BackendBundle\Entity\UserPermission:
    type: entity
    repositoryClass: BackendBundle\Repository\UserPermissionRepository
    table: user_permission
    indexes:
        user:
            columns:
                - user
    uniqueConstraints:
        user_2:
            columns:
                - user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
# USER ###########################################################
        userCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: user_create
        userEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: user_edit
        userRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: user_remove
        userDumpView:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: user_dump_view
        userPermission:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: user_permission
# /USER ##########################################################
# CLINIC #########################################################
        clinicViewOther:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: clinic_view_other
        clinicCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: clinic_create
        clinicEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: clinic_edit
        clinicRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: clinic_remove
# /CLINIC ########################################################
# MEDICAL HISTORY ################################################
        medicalHistoryCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_create
        medicalHistoryEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_edit
        medicalHistoryRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_remove
        medicalHistoryRegistrationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_registration_date_edit
        medicalHistoryUserRegistererEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_user_registerer_edit
        medicalHistoryModificationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_modification_date_edit
        medicalHistoryUserModifierEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_user_modifier_edit
# /MEDICAL HISTORY ###############################################
# MEDICAL HISTORY DOC ############################################
        medicalHistoryDocCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_create
        medicalHistoryDocEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_edit
        medicalHistoryDocRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_remove
        medicalHistoryDocRegistrationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_registration_date_edit
        medicalHistoryDocUserRegistererEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_user_registerer_edit
        medicalHistoryDocModificationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_modification_date_edit
        medicalHistoryDocUserModifierEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: medical_history_doc_user_modifier_edit
# /MEDICAL HISTORY DOC ###########################################
# ORTHOPODOLOGY HISTORY ##########################################
        orthopodologyHistoryCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_create
        orthopodologyHistoryEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_edit
        orthopodologyHistoryRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_remove
        orthopodologyHistoryRegistrationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_registration_date_edit
        orthopodologyHistoryUserRegistererEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_user_registerer_edit
        orthopodologyHistoryModificationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_modification_date_edit
        orthopodologyHistoryUserModifierEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_user_modifier_edit
# /ORTHOPODOLOGY HISTORY #########################################
# ORTHOPODOLOGY HISTORY DOC ######################################
        orthopodologyHistoryDocCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_create
        orthopodologyHistoryDocEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_edit
        orthopodologyHistoryDocRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_remove
        orthopodologyHistoryDocRegistrationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_registration_date_edit
        orthopodologyHistoryDocUserRegistererEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_user_registerer_edit
        orthopodologyHistoryDocModificationDateEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_modification_date_edit
        orthopodologyHistoryDocUserModifierEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: orthopodology_history_doc_user_modifier_edit
# /ORTHOPODOLOGY HISTORY DOC #####################################
# SERVICE ########################################################
        serviceCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: service_create
        serviceEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: service_edit
        serviceRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: service_remove
# /SERVICE #######################################################
# TRACING ########################################################
        tracingCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_create
        tracingEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_edit
        tracingRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_remove
# /TRACING #######################################################
# TRACING SERVICE ################################################
        tracingServiceCreate:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_service_create
        tracingServiceEdit:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_service_edit
        tracingServiceRemove:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: tracing_service_remove
# /TRACING SERVICE ###############################################
# ADMIN ##########################################################
        adminSectionAccess:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: admin_section_access
        adminGeneralDataAccess:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: admin_general_data_access
# /ADMIN #########################################################
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
