BackendBundle\Entity\UserPermissionDefinition:
    type: entity
    table: user_permission_definition
# indexes #############################################################     
# /indexes ############################################################ 
# uniqueConstraints####################################################       
# /uniqueConstraints###################################################               
# id ##################################################################
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
# /id #################################################################
# fields ############################################################## 
    fields:
    # USER ############################################################
        userList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_list
        userView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_view
        userCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_create
        userEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_edit
        userRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_remove
        userDumpView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_dump_view
        userPermission:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_permission
        clinicViewOther:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_view_other
    # /USER ###########################################################
    # CLINIC ##########################################################
        clinicList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_list
        clinicView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_view                
        clinicCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_create
        clinicEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_edit
        clinicRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: clinic_remove
    # /CLINIC #########################################################
    # MEDICAL HISTORY #################################################
        medicalHistoryList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_list
        medicalHistoryView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_view
        medicalHistoryCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_create
        medicalHistoryEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_edit
        medicalHistoryRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_remove
        medicalHistoryRegistrationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_registration_date_edit
        medicalHistoryModificationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_modification_date_edit
        medicalHistoryUserRegistererEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_user_registerer_edit
        medicalHistoryUserModifierEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_user_modifier_edit
    # /MEDICAL HISTORY ################################################
    # MEDICAL HISTORY DOC #############################################
        medicalHistoryDocList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_list
        medicalHistoryDocView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_view
        medicalHistoryDocCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_create
        medicalHistoryDocEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_edit
        medicalHistoryDocRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_remove
        medicalHistoryDocRegistrationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_registration_date_edit
        medicalHistoryDocUserRegistererEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_user_registerer_edit
        medicalHistoryDocModificationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_modification_date_edit
        medicalHistoryDocUserModifierEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: medical_history_doc_user_modifier_edit
    # /MEDICAL HISTORY DOC ############################################
    # ORTHOPODOLOGY HISTORY ###########################################
        orthopodologyHistoryList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_list
        orthopodologyHistoryView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_view
        orthopodologyHistoryCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_create
        orthopodologyHistoryEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_edit
        orthopodologyHistoryRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_remove
        orthopodologyHistoryRegistrationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_registration_date_edit
        orthopodologyHistoryUserRegistererEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_user_registerer_edit
        orthopodologyHistoryModificationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_modification_date_edit
        orthopodologyHistoryUserModifierEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_user_modifier_edit
    # /ORTHOPODOLOGY HISTORY ##########################################
    # ORTHOPODOLOGY HISTORY DOC #######################################
        orthopodologyHistoryDocList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_list
        orthopodologyHistoryDocView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_view
        orthopodologyHistoryDocCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_create
        orthopodologyHistoryDocEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_edit
        orthopodologyHistoryDocRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_remove
        orthopodologyHistoryDocRegistrationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_registration_date_edit
        orthopodologyHistoryDocUserRegistererEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_user_registerer_edit
        orthopodologyHistoryDocModificationDateEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_modification_date_edit
        orthopodologyHistoryDocUserModifierEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: orthopodology_history_doc_user_modifier_edit
    # /ORTHOPODOLOGY HISTORY DOC ######################################
    # REPORT ##########################################################
        reportList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: report_list
        reportView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: report_view            
        reportCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: report_create            
        reportEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: report_edit
        reportRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: report_remove                        
    # /REPORT #########################################################
    # INVOICE #########################################################
        invoiceList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: invoice_list
        invoiceView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: invoice_view
        invoiceCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: invoice_create
        invoiceEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: invoice_edit
        invoiceRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: invoice_remove
    # /INVOICE ########################################################
    # SERVICE #########################################################
        serviceList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: service_list
        serviceView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: service_view
        serviceCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: service_create
        serviceEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: service_edit
        serviceRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: service_remove
    # /SERVICE ########################################################
    # SCHEDULE ########################################################
        scheduleList:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: schedule_list
        scheduleView:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: schedule_view
        scheduleCreate:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: schedule_create
        scheduleEdit:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: schedule_edit
        scheduleRemove:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: schedule_remove
    # /SCHEDULE #######################################################
    # TRACING #########################################################
        tracingList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_list
        tracingView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_view
        tracingCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_create
        tracingEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_edit
        tracingRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_remove
    # /TRACING ########################################################
    # TRACING SERVICE #################################################
        tracingServiceList:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_service_list
        tracingServiceView:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_service_view
        tracingServiceCreate:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_service_create
        tracingServiceEdit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_service_edit
        tracingServiceRemove:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: tracing_service_remove
        tracingServiceChangeCountableStatus:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: tracing_service_change_countable_status              
    # /TRACING SERVICE ################################################
    # ADMIN ###########################################################
        adminSectionAccess:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: admin_section_access
        adminGeneralDataAccess:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: admin_general_data_access
    # /ADMIN ##########################################################
# /fields #############################################################
# manyToOne ########################################################### 
# /manyToOne ##########################################################
# oneToMany ########################################################### 
# /oneToMany ########################################################## 
    lifecycleCallbacks: {  }
